# coding: utf-8

# flake8: noqa

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning & deprecation  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.  ## AI assistant access (MCP)  In addition to this REST API, this deployment exposes a **Model Context Protocol (MCP)** interface that lets AI assistants query GraphSense directly in natural language, without writing code against the endpoints below.  The MCP interface is available at the `/mcp` path of this server, relative to the address this documentation is served from. It offers a curated selection of the most useful operations, so an assistant can answer questions about addresses, transactions, clusters, and tags on your behalf.  To use it, add that `/mcp` URL to an MCP-capable assistant as a new connector or tool source; the assistant then handles the rest.  **Authentication:** the MCP endpoint is protected by OAuth. When adding the connector in your assistant, use the client ID `iknaio-mcp`.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "2.15.0-rc.3"

# Define package exports
__all__ = [
    "AddressesApi",
    "BlocksApi",
    "BulkApi",
    "ClustersApi",
    "EntitiesApi",
    "GeneralApi",
    "GraphApi",
    "RatesApi",
    "TagsApi",
    "TokensApi",
    "TxsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Actor",
    "ActorContext",
    "Address",
    "AddressOutput",
    "AddressTag",
    "AddressTags",
    "AddressTx",
    "AddressTxUtxo",
    "AddressTxs",
    "Block",
    "BlockAtDate",
    "ChangeHeuristics",
    "Cluster",
    "ClusterAddresses",
    "CoinJoinConsensus",
    "CoinJoinHeuristics",
    "Concept",
    "ConsensusEntry",
    "CurrencyStats",
    "DirectChangeHeuristic",
    "Entity",
    "EntityAddresses",
    "ExternalConversion",
    "GraphAddressNetworkSummary",
    "GraphAddressOverall",
    "GraphAddressRef",
    "GraphAddressSummary",
    "GraphCompareNote",
    "GraphCompareRequest",
    "GraphCompareSignal",
    "GraphCompareVerdict",
    "GraphComparedTx",
    "GraphComparison",
    "GraphLineageEdge",
    "GraphNote",
    "GraphSummary",
    "GraphSummaryRequest",
    "GraphTxCharacteristics",
    "GraphTxNetworkSummary",
    "GraphTxOverall",
    "GraphTxRef",
    "GraphTxSummary",
    "HTTPValidationError",
    "JoinMarketHeuristic",
    "LabelSummary",
    "LabeledItemRef",
    "Link",
    "LinkUtxo",
    "Links",
    "LinksInner",
    "LocationInner",
    "MultiInputChangeHeuristic",
    "NeighborAddress",
    "NeighborAddresses",
    "NeighborCluster",
    "NeighborClusters",
    "NeighborEntities",
    "NeighborEntity",
    "OneTimeChangeHeuristic",
    "PerTxInner",
    "Rate",
    "Rates",
    "RelatedAddress",
    "RelatedAddresses",
    "SearchResult",
    "SearchResultByCurrency",
    "SearchResultLevel1",
    "SearchResultLevel2",
    "SearchResultLevel3",
    "SearchResultLevel4",
    "SearchResultLevel5",
    "SearchResultLevel6",
    "Stats",
    "Tag",
    "TagCloudEntry",
    "TagSummary",
    "Taxonomy",
    "TokenConfig",
    "TokenConfigs",
    "Tx",
    "TxAccount",
    "TxRef",
    "TxSummary",
    "TxUtxo",
    "TxValue",
    "UserReportedTag",
    "UserTagReportResponse",
    "UtxoHeuristics",
    "ValidationError",
    "Values",
    "WasabiHeuristic",
    "WhirlpoolCoinJoinHeuristic",
    "WhirlpoolTx0Heuristic",
]

# Import compat module first to apply BaseModel patches
import graphsense.compat  # noqa: F401

# import apis into sdk package
from graphsense.api.addresses_api import AddressesApi as AddressesApi
from graphsense.api.blocks_api import BlocksApi as BlocksApi
from graphsense.api.bulk_api import BulkApi as BulkApi
from graphsense.api.clusters_api import ClustersApi as ClustersApi
from graphsense.api.entities_api import EntitiesApi as EntitiesApi
from graphsense.api.general_api import GeneralApi as GeneralApi
from graphsense.api.graph_api import GraphApi as GraphApi
from graphsense.api.rates_api import RatesApi as RatesApi
from graphsense.api.tags_api import TagsApi as TagsApi
from graphsense.api.tokens_api import TokensApi as TokensApi
from graphsense.api.txs_api import TxsApi as TxsApi

# import ApiClient
from graphsense.api_response import ApiResponse as ApiResponse
from graphsense.api_client import ApiClient as ApiClient
from graphsense.configuration import Configuration as Configuration
from graphsense.exceptions import OpenApiException as OpenApiException
from graphsense.exceptions import ApiTypeError as ApiTypeError
from graphsense.exceptions import ApiValueError as ApiValueError
from graphsense.exceptions import ApiKeyError as ApiKeyError
from graphsense.exceptions import ApiAttributeError as ApiAttributeError
from graphsense.exceptions import ApiException as ApiException

# import models into sdk package
from graphsense.models.actor import Actor as Actor
from graphsense.models.actor_context import ActorContext as ActorContext
from graphsense.models.address import Address as Address
from graphsense.models.address_output import AddressOutput as AddressOutput
from graphsense.models.address_tag import AddressTag as AddressTag
from graphsense.models.address_tags import AddressTags as AddressTags
from graphsense.models.address_tx import AddressTx as AddressTx
from graphsense.models.address_tx_utxo import AddressTxUtxo as AddressTxUtxo
from graphsense.models.address_txs import AddressTxs as AddressTxs
from graphsense.models.block import Block as Block
from graphsense.models.block_at_date import BlockAtDate as BlockAtDate
from graphsense.models.change_heuristics import ChangeHeuristics as ChangeHeuristics
from graphsense.models.cluster import Cluster as Cluster
from graphsense.models.cluster_addresses import ClusterAddresses as ClusterAddresses
from graphsense.models.coin_join_consensus import CoinJoinConsensus as CoinJoinConsensus
from graphsense.models.coin_join_heuristics import CoinJoinHeuristics as CoinJoinHeuristics
from graphsense.models.concept import Concept as Concept
from graphsense.models.consensus_entry import ConsensusEntry as ConsensusEntry
from graphsense.models.currency_stats import CurrencyStats as CurrencyStats
from graphsense.models.direct_change_heuristic import DirectChangeHeuristic as DirectChangeHeuristic
from graphsense.models.entity import Entity as Entity
from graphsense.models.entity_addresses import EntityAddresses as EntityAddresses
from graphsense.models.external_conversion import ExternalConversion as ExternalConversion
from graphsense.models.graph_address_network_summary import GraphAddressNetworkSummary as GraphAddressNetworkSummary
from graphsense.models.graph_address_overall import GraphAddressOverall as GraphAddressOverall
from graphsense.models.graph_address_ref import GraphAddressRef as GraphAddressRef
from graphsense.models.graph_address_summary import GraphAddressSummary as GraphAddressSummary
from graphsense.models.graph_compare_note import GraphCompareNote as GraphCompareNote
from graphsense.models.graph_compare_request import GraphCompareRequest as GraphCompareRequest
from graphsense.models.graph_compare_signal import GraphCompareSignal as GraphCompareSignal
from graphsense.models.graph_compare_verdict import GraphCompareVerdict as GraphCompareVerdict
from graphsense.models.graph_compared_tx import GraphComparedTx as GraphComparedTx
from graphsense.models.graph_comparison import GraphComparison as GraphComparison
from graphsense.models.graph_lineage_edge import GraphLineageEdge as GraphLineageEdge
from graphsense.models.graph_note import GraphNote as GraphNote
from graphsense.models.graph_summary import GraphSummary as GraphSummary
from graphsense.models.graph_summary_request import GraphSummaryRequest as GraphSummaryRequest
from graphsense.models.graph_tx_characteristics import GraphTxCharacteristics as GraphTxCharacteristics
from graphsense.models.graph_tx_network_summary import GraphTxNetworkSummary as GraphTxNetworkSummary
from graphsense.models.graph_tx_overall import GraphTxOverall as GraphTxOverall
from graphsense.models.graph_tx_ref import GraphTxRef as GraphTxRef
from graphsense.models.graph_tx_summary import GraphTxSummary as GraphTxSummary
from graphsense.models.http_validation_error import HTTPValidationError as HTTPValidationError
from graphsense.models.join_market_heuristic import JoinMarketHeuristic as JoinMarketHeuristic
from graphsense.models.label_summary import LabelSummary as LabelSummary
from graphsense.models.labeled_item_ref import LabeledItemRef as LabeledItemRef
from graphsense.models.link import Link as Link
from graphsense.models.link_utxo import LinkUtxo as LinkUtxo
from graphsense.models.links import Links as Links
from graphsense.models.links_inner import LinksInner as LinksInner
from graphsense.models.location_inner import LocationInner as LocationInner
from graphsense.models.multi_input_change_heuristic import MultiInputChangeHeuristic as MultiInputChangeHeuristic
from graphsense.models.neighbor_address import NeighborAddress as NeighborAddress
from graphsense.models.neighbor_addresses import NeighborAddresses as NeighborAddresses
from graphsense.models.neighbor_cluster import NeighborCluster as NeighborCluster
from graphsense.models.neighbor_clusters import NeighborClusters as NeighborClusters
from graphsense.models.neighbor_entities import NeighborEntities as NeighborEntities
from graphsense.models.neighbor_entity import NeighborEntity as NeighborEntity
from graphsense.models.one_time_change_heuristic import OneTimeChangeHeuristic as OneTimeChangeHeuristic
from graphsense.models.per_tx_inner import PerTxInner as PerTxInner
from graphsense.models.rate import Rate as Rate
from graphsense.models.rates import Rates as Rates
from graphsense.models.related_address import RelatedAddress as RelatedAddress
from graphsense.models.related_addresses import RelatedAddresses as RelatedAddresses
from graphsense.models.search_result import SearchResult as SearchResult
from graphsense.models.search_result_by_currency import SearchResultByCurrency as SearchResultByCurrency
from graphsense.models.search_result_level1 import SearchResultLevel1 as SearchResultLevel1
from graphsense.models.search_result_level2 import SearchResultLevel2 as SearchResultLevel2
from graphsense.models.search_result_level3 import SearchResultLevel3 as SearchResultLevel3
from graphsense.models.search_result_level4 import SearchResultLevel4 as SearchResultLevel4
from graphsense.models.search_result_level5 import SearchResultLevel5 as SearchResultLevel5
from graphsense.models.search_result_level6 import SearchResultLevel6 as SearchResultLevel6
from graphsense.models.stats import Stats as Stats
from graphsense.models.tag import Tag as Tag
from graphsense.models.tag_cloud_entry import TagCloudEntry as TagCloudEntry
from graphsense.models.tag_summary import TagSummary as TagSummary
from graphsense.models.taxonomy import Taxonomy as Taxonomy
from graphsense.models.token_config import TokenConfig as TokenConfig
from graphsense.models.token_configs import TokenConfigs as TokenConfigs
from graphsense.models.tx import Tx as Tx
from graphsense.models.tx_account import TxAccount as TxAccount
from graphsense.models.tx_ref import TxRef as TxRef
from graphsense.models.tx_summary import TxSummary as TxSummary
from graphsense.models.tx_utxo import TxUtxo as TxUtxo
from graphsense.models.tx_value import TxValue as TxValue
from graphsense.models.user_reported_tag import UserReportedTag as UserReportedTag
from graphsense.models.user_tag_report_response import UserTagReportResponse as UserTagReportResponse
from graphsense.models.utxo_heuristics import UtxoHeuristics as UtxoHeuristics
from graphsense.models.validation_error import ValidationError as ValidationError
from graphsense.models.values import Values as Values
from graphsense.models.wasabi_heuristic import WasabiHeuristic as WasabiHeuristic
from graphsense.models.whirlpool_coin_join_heuristic import WhirlpoolCoinJoinHeuristic as WhirlpoolCoinJoinHeuristic
from graphsense.models.whirlpool_tx0_heuristic import WhirlpoolTx0Heuristic as WhirlpoolTx0Heuristic

