# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, entities, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.consensus_entry import ConsensusEntry
from graphsense.models.direct_change_heuristic import DirectChangeHeuristic
from graphsense.models.multi_input_change_heuristic import MultiInputChangeHeuristic
from graphsense.models.one_time_change_heuristic import OneTimeChangeHeuristic
from typing import Optional, Set
from typing_extensions import Self

class ChangeHeuristics(BaseModel):
    """
    ChangeHeuristics
    """ # noqa: E501
    consensus: List[ConsensusEntry]
    one_time_change: Optional[OneTimeChangeHeuristic] = None
    direct_change: Optional[DirectChangeHeuristic] = None
    multi_input_change: Optional[MultiInputChangeHeuristic] = None
    __properties: ClassVar[List[str]] = ["consensus", "one_time_change", "direct_change", "multi_input_change"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChangeHeuristics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in consensus (list)
        _items = []
        if self.consensus:
            for _item_consensus in self.consensus:
                if _item_consensus:
                    _items.append(_item_consensus.to_dict())
            _dict['consensus'] = _items
        # override the default output from pydantic by calling `to_dict()` of one_time_change
        if self.one_time_change:
            _dict['one_time_change'] = self.one_time_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of direct_change
        if self.direct_change:
            _dict['direct_change'] = self.direct_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of multi_input_change
        if self.multi_input_change:
            _dict['multi_input_change'] = self.multi_input_change.to_dict()

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChangeHeuristics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "consensus": [ConsensusEntry.from_dict(_item) for _item in obj["consensus"]] if obj.get("consensus") is not None else None,
            "one_time_change": OneTimeChangeHeuristic.from_dict(obj["one_time_change"]) if obj.get("one_time_change") is not None else None,
            "direct_change": DirectChangeHeuristic.from_dict(obj["direct_change"]) if obj.get("direct_change") is not None else None,
            "multi_input_change": MultiInputChangeHeuristic.from_dict(obj["multi_input_change"]) if obj.get("multi_input_change") is not None else None
        })
        return _obj


