# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning and deprecation policy  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.coin_join_consensus import CoinJoinConsensus
from graphsense.models.join_market_heuristic import JoinMarketHeuristic
from graphsense.models.wasabi_heuristic import WasabiHeuristic
from graphsense.models.whirlpool_coin_join_heuristic import WhirlpoolCoinJoinHeuristic
from graphsense.models.whirlpool_tx0_heuristic import WhirlpoolTx0Heuristic
from typing import Optional, Set
from typing_extensions import Self

class CoinJoinHeuristics(BaseModel):
    """
    CoinJoinHeuristics
    """ # noqa: E501
    consensus: Optional[CoinJoinConsensus] = None
    joinmarket: Optional[JoinMarketHeuristic] = None
    wasabi: Optional[WasabiHeuristic] = None
    whirlpool_tx0: Optional[WhirlpoolTx0Heuristic] = None
    whirlpool_coinjoin: Optional[WhirlpoolCoinJoinHeuristic] = None
    __properties: ClassVar[List[str]] = ["consensus", "joinmarket", "wasabi", "whirlpool_tx0", "whirlpool_coinjoin"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoinJoinHeuristics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of consensus
        if self.consensus:
            _dict['consensus'] = self.consensus.to_dict()
        # override the default output from pydantic by calling `to_dict()` of joinmarket
        if self.joinmarket:
            _dict['joinmarket'] = self.joinmarket.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wasabi
        if self.wasabi:
            _dict['wasabi'] = self.wasabi.to_dict()
        # override the default output from pydantic by calling `to_dict()` of whirlpool_tx0
        if self.whirlpool_tx0:
            _dict['whirlpool_tx0'] = self.whirlpool_tx0.to_dict()
        # override the default output from pydantic by calling `to_dict()` of whirlpool_coinjoin
        if self.whirlpool_coinjoin:
            _dict['whirlpool_coinjoin'] = self.whirlpool_coinjoin.to_dict()

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoinJoinHeuristics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "consensus": CoinJoinConsensus.from_dict(obj["consensus"]) if obj.get("consensus") is not None else None,
            "joinmarket": JoinMarketHeuristic.from_dict(obj["joinmarket"]) if obj.get("joinmarket") is not None else None,
            "wasabi": WasabiHeuristic.from_dict(obj["wasabi"]) if obj.get("wasabi") is not None else None,
            "whirlpool_tx0": WhirlpoolTx0Heuristic.from_dict(obj["whirlpool_tx0"]) if obj.get("whirlpool_tx0") is not None else None,
            "whirlpool_coinjoin": WhirlpoolCoinJoinHeuristic.from_dict(obj["whirlpool_coinjoin"]) if obj.get("whirlpool_coinjoin") is not None else None
        })
        return _obj


