# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning and deprecation policy  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ExternalConversion(BaseModel):
    """
    External conversion (DEX swap or bridge) model.
    """ # noqa: E501
    conversion_type: StrictStr
    from_address: StrictStr
    to_address: StrictStr
    from_asset: StrictStr
    to_asset: StrictStr
    from_amount: StrictStr
    to_amount: StrictStr
    from_asset_transfer: StrictStr
    to_asset_transfer: StrictStr
    from_network: StrictStr
    to_network: StrictStr
    from_is_supported_asset: StrictBool
    to_is_supported_asset: StrictBool
    __properties: ClassVar[List[str]] = ["conversion_type", "from_address", "to_address", "from_asset", "to_asset", "from_amount", "to_amount", "from_asset_transfer", "to_asset_transfer", "from_network", "to_network", "from_is_supported_asset", "to_is_supported_asset"]

    @field_validator('conversion_type')
    def conversion_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['dex_swap', 'bridge_tx']):
            raise ValueError("must be one of enum values ('dex_swap', 'bridge_tx')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalConversion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalConversion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conversion_type": obj.get("conversion_type"),
            "from_address": obj.get("from_address"),
            "to_address": obj.get("to_address"),
            "from_asset": obj.get("from_asset"),
            "to_asset": obj.get("to_asset"),
            "from_amount": obj.get("from_amount"),
            "to_amount": obj.get("to_amount"),
            "from_asset_transfer": obj.get("from_asset_transfer"),
            "to_asset_transfer": obj.get("to_asset_transfer"),
            "from_network": obj.get("from_network"),
            "to_network": obj.get("to_network"),
            "from_is_supported_asset": obj.get("from_is_supported_asset"),
            "to_is_supported_asset": obj.get("to_is_supported_asset")
        })
        return _obj


