# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning & deprecation  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.  ## AI assistant access (MCP)  In addition to this REST API, this deployment exposes a **Model Context Protocol (MCP)** interface that lets AI assistants query GraphSense directly in natural language, without writing code against the endpoints below.  The MCP interface is available at the `/mcp` path of this server, relative to the address this documentation is served from. It offers a curated selection of the most useful operations, so an assistant can answer questions about addresses, transactions, clusters, and tags on your behalf.  To use it, add that `/mcp` URL to an MCP-capable assistant as a new connector or tool source; the assistant then handles the rest.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.graph_note import GraphNote
from graphsense.models.values import Values
from typing import Optional, Set
from typing_extensions import Self

class GraphTxNetworkSummary(BaseModel):
    """
    Aggregate stats over one network's transactions.  ``total_value.value`` is the network's native base unit (satoshi for UTXO, wei/sun for account chains) and sums native transfers only; ``total_value.fiat_values`` sum per fiat code across all transfers, including tokens. ``total_fee`` stays in the native unit. ``total_inputs`` / ``total_outputs`` are UTXO-only and omitted for account-model summaries. ``notes`` flags caveats. ``assets`` lists the distinct assets involved on this network (lowercase, native first then tokens sorted).
    """ # noqa: E501
    network: StrictStr
    tx_count: StrictInt
    total_value: Values
    total_fee: Optional[StrictInt] = None
    total_inputs: Optional[StrictInt] = None
    total_outputs: Optional[StrictInt] = None
    block_min: StrictInt
    block_max: StrictInt
    timestamp_min: StrictInt
    timestamp_max: StrictInt
    notes: Optional[List[GraphNote]] = None
    assets: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["network", "tx_count", "total_value", "total_fee", "total_inputs", "total_outputs", "block_min", "block_max", "timestamp_min", "timestamp_max", "notes", "assets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphTxNetworkSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of total_value
        if self.total_value:
            _dict['total_value'] = self.total_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item_notes in self.notes:
                if _item_notes:
                    _items.append(_item_notes.to_dict())
            _dict['notes'] = _items

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphTxNetworkSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "network": obj.get("network"),
            "tx_count": obj.get("tx_count"),
            "total_value": Values.from_dict(obj["total_value"]) if obj.get("total_value") is not None else None,
            "total_fee": obj.get("total_fee"),
            "total_inputs": obj.get("total_inputs"),
            "total_outputs": obj.get("total_outputs"),
            "block_min": obj.get("block_min"),
            "block_max": obj.get("block_max"),
            "timestamp_min": obj.get("timestamp_min"),
            "timestamp_max": obj.get("timestamp_max"),
            "notes": [GraphNote.from_dict(_item) for _item in obj["notes"]] if obj.get("notes") is not None else None,
            "assets": obj.get("assets")
        })
        return _obj


