# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning & deprecation  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.  ## AI assistant access (MCP)  In addition to this REST API, this deployment exposes a **Model Context Protocol (MCP)** interface that lets AI assistants query GraphSense directly in natural language, without writing code against the endpoints below.  The MCP interface is available at the `/mcp` path of this server, relative to the address this documentation is served from. It offers a curated selection of the most useful operations, so an assistant can answer questions about addresses, transactions, clusters, and tags on your behalf.  To use it, add that `/mcp` URL to an MCP-capable assistant as a new connector or tool source; the assistant then handles the rest.  **Authentication:** the MCP endpoint is protected by OAuth. When adding the connector in your assistant, use the client ID `iknaio-mcp`.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.graph_compare_signal import GraphCompareSignal
from graphsense.models.graph_compare_verdict import GraphCompareVerdict
from graphsense.models.graph_compared_tx import GraphComparedTx
from graphsense.models.graph_lineage_edge import GraphLineageEdge
from typing import Optional, Set
from typing_extensions import Self

class GraphComparison(BaseModel):
    """
    Top-level response for /graph/compare.
    """ # noqa: E501
    txs: List[GraphComparedTx]
    signals: Optional[List[GraphCompareSignal]] = None
    lineage: Optional[List[GraphLineageEdge]] = None
    verdict: Optional[GraphCompareVerdict] = None
    __properties: ClassVar[List[str]] = ["txs", "signals", "lineage", "verdict"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphComparison from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in txs (list)
        _items = []
        if self.txs:
            for _item_txs in self.txs:
                if _item_txs:
                    _items.append(_item_txs.to_dict())
            _dict['txs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in signals (list)
        _items = []
        if self.signals:
            for _item_signals in self.signals:
                if _item_signals:
                    _items.append(_item_signals.to_dict())
            _dict['signals'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in lineage (list)
        _items = []
        if self.lineage:
            for _item_lineage in self.lineage:
                if _item_lineage:
                    _items.append(_item_lineage.to_dict())
            _dict['lineage'] = _items
        # override the default output from pydantic by calling `to_dict()` of verdict
        if self.verdict:
            _dict['verdict'] = self.verdict.to_dict()

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphComparison from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "txs": [GraphComparedTx.from_dict(_item) for _item in obj["txs"]] if obj.get("txs") is not None else None,
            "signals": [GraphCompareSignal.from_dict(_item) for _item in obj["signals"]] if obj.get("signals") is not None else None,
            "lineage": [GraphLineageEdge.from_dict(_item) for _item in obj["lineage"]] if obj.get("lineage") is not None else None,
            "verdict": GraphCompareVerdict.from_dict(obj["verdict"]) if obj.get("verdict") is not None else None
        })
        return _obj


