# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning & deprecation  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.  ## AI assistant access (MCP)  In addition to this REST API, this deployment exposes a **Model Context Protocol (MCP)** interface that lets AI assistants query GraphSense directly in natural language, without writing code against the endpoints below.  The MCP interface is available at the `/mcp` path of this server, relative to the address this documentation is served from. It offers a curated selection of the most useful operations, so an assistant can answer questions about addresses, transactions, clusters, and tags on your behalf.  To use it, add that `/mcp` URL to an MCP-capable assistant as a new connector or tool source; the assistant then handles the rest.  **Authentication:** the MCP endpoint is protected by OAuth. When adding the connector in your assistant, use the client ID `iknaio-mcp`.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.graph_note import GraphNote
from graphsense.models.labeled_item_ref import LabeledItemRef
from graphsense.models.values import Values
from typing import Optional, Set
from typing_extensions import Self

class GraphAddressNetworkSummary(BaseModel):
    """
    Aggregate stats over one network's addresses. Value totals follow the ``Values`` pattern (native base unit plus per-code fiat sums); token holdings are excluded from native totals (noted). ``assets`` lists the distinct assets involved on this network (lowercase, native first then tokens sorted).
    """ # noqa: E501
    network: StrictStr
    address_count: StrictInt
    total_received: Values
    total_spent: Values
    balance: Values
    first_usage: Optional[StrictInt] = None
    last_usage: Optional[StrictInt] = None
    tagged_address_count: Optional[StrictInt] = 0
    actors: Optional[List[LabeledItemRef]] = None
    notes: Optional[List[GraphNote]] = None
    assets: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["network", "address_count", "total_received", "total_spent", "balance", "first_usage", "last_usage", "tagged_address_count", "actors", "notes", "assets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphAddressNetworkSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of total_received
        if self.total_received:
            _dict['total_received'] = self.total_received.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_spent
        if self.total_spent:
            _dict['total_spent'] = self.total_spent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of balance
        if self.balance:
            _dict['balance'] = self.balance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in actors (list)
        _items = []
        if self.actors:
            for _item_actors in self.actors:
                if _item_actors:
                    _items.append(_item_actors.to_dict())
            _dict['actors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item_notes in self.notes:
                if _item_notes:
                    _items.append(_item_notes.to_dict())
            _dict['notes'] = _items

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphAddressNetworkSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "network": obj.get("network"),
            "address_count": obj.get("address_count"),
            "total_received": Values.from_dict(obj["total_received"]) if obj.get("total_received") is not None else None,
            "total_spent": Values.from_dict(obj["total_spent"]) if obj.get("total_spent") is not None else None,
            "balance": Values.from_dict(obj["balance"]) if obj.get("balance") is not None else None,
            "first_usage": obj.get("first_usage"),
            "last_usage": obj.get("last_usage"),
            "tagged_address_count": obj.get("tagged_address_count") if obj.get("tagged_address_count") is not None else 0,
            "actors": [LabeledItemRef.from_dict(_item) for _item in obj["actors"]] if obj.get("actors") is not None else None,
            "notes": [GraphNote.from_dict(_item) for _item in obj["notes"]] if obj.get("notes") is not None else None,
            "assets": obj.get("assets")
        })
        return _obj


