# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning & deprecation  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.  ## AI assistant access (MCP)  In addition to this REST API, this deployment exposes a **Model Context Protocol (MCP)** interface that lets AI assistants query GraphSense directly in natural language, without writing code against the endpoints below.  The MCP interface is available at the `/mcp` path of this server, relative to the address this documentation is served from. It offers a curated selection of the most useful operations, so an assistant can answer questions about addresses, transactions, clusters, and tags on your behalf.  To use it, add that `/mcp` URL to an MCP-capable assistant as a new connector or tool source; the assistant then handles the rest.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from graphsense.models.labeled_item_ref import LabeledItemRef
from typing import Optional, Set
from typing_extensions import Self

class SubgraphAddressSummary(BaseModel):
    """
    Aggregate stats over the addresses in a subgraph.  Value totals are in the chain's base unit; the ``*_fiat`` fields sum the ``fiat_currency`` value across the set. ``first_usage`` / ``last_usage`` span the set's on-chain activity and are omitted when no selected address has any. ``tagged_address_count`` counts addresses with at least one visible tag; ``actors`` lists the distinct actors across all tags on the set. ``notes`` flags caveats (partial fiat totals, token holdings excluded from native totals).
    """ # noqa: E501
    address_count: StrictInt
    total_received: StrictInt
    total_received_fiat: Optional[Union[StrictFloat, StrictInt]] = None
    total_spent: StrictInt
    total_spent_fiat: Optional[Union[StrictFloat, StrictInt]] = None
    balance: StrictInt
    balance_fiat: Optional[Union[StrictFloat, StrictInt]] = None
    fiat_currency: Optional[StrictStr] = 'usd'
    first_usage: Optional[StrictInt] = None
    last_usage: Optional[StrictInt] = None
    tagged_address_count: Optional[StrictInt] = 0
    actors: Optional[List[LabeledItemRef]] = None
    notes: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["address_count", "total_received", "total_received_fiat", "total_spent", "total_spent_fiat", "balance", "balance_fiat", "fiat_currency", "first_usage", "last_usage", "tagged_address_count", "actors", "notes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubgraphAddressSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in actors (list)
        _items = []
        if self.actors:
            for _item_actors in self.actors:
                if _item_actors:
                    _items.append(_item_actors.to_dict())
            _dict['actors'] = _items

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubgraphAddressSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address_count": obj.get("address_count"),
            "total_received": obj.get("total_received"),
            "total_received_fiat": obj.get("total_received_fiat"),
            "total_spent": obj.get("total_spent"),
            "total_spent_fiat": obj.get("total_spent_fiat"),
            "balance": obj.get("balance"),
            "balance_fiat": obj.get("balance_fiat"),
            "fiat_currency": obj.get("fiat_currency") if obj.get("fiat_currency") is not None else 'usd',
            "first_usage": obj.get("first_usage"),
            "last_usage": obj.get("last_usage"),
            "tagged_address_count": obj.get("tagged_address_count") if obj.get("tagged_address_count") is not None else 0,
            "actors": [LabeledItemRef.from_dict(_item) for _item in obj["actors"]] if obj.get("actors") is not None else None,
            "notes": obj.get("notes")
        })
        return _obj


