# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning & deprecation  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.  ## AI assistant access (MCP)  In addition to this REST API, this deployment exposes a **Model Context Protocol (MCP)** interface that lets AI assistants query GraphSense directly in natural language, without writing code against the endpoints below.  The MCP interface is available at the `/mcp` path of this server, relative to the address this documentation is served from. It offers a curated selection of the most useful operations, so an assistant can answer questions about addresses, transactions, clusters, and tags on your behalf.  To use it, add that `/mcp` URL to an MCP-capable assistant as a new connector or tool source; the assistant then handles the rest.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TxCharacteristics(BaseModel):
    """
    Extracted characteristics for a single transaction.  ``input_script_types`` / ``output_script_types`` hold the distinct script types observed across the inputs/outputs, sorted for stable output. Empty list means none could be derived from address strings.  Several internal fields are intentionally omitted from the API surface because the same information is exposed via the corresponding signals (``rbf``, ``witness_present``, ``bip69_outputs_sorted``, ``exchange_input_overlap``) and on-chain edge collections (``input_addresses_canon``, ``change_addresses_canon``, ``parent_tx_hashes``, ``utxo_parent_indexes``). Surface them here if a consumer needs the per-tx booleans alongside the comparison verdict.
    """ # noqa: E501
    input_script_types: Optional[List[StrictStr]] = None
    output_script_types: Optional[List[StrictStr]] = None
    n_inputs: StrictInt
    n_outputs: StrictInt
    total_input_sat: StrictInt
    total_output_sat: StrictInt
    fee_sat: Optional[StrictInt] = None
    tx_version: Optional[StrictInt] = None
    locktime: Optional[StrictInt] = None
    input_cluster_ids: Optional[List[StrictInt]] = None
    coinjoin_detected: Optional[StrictBool] = False
    coinjoin_protocol: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["input_script_types", "output_script_types", "n_inputs", "n_outputs", "total_input_sat", "total_output_sat", "fee_sat", "tx_version", "locktime", "input_cluster_ids", "coinjoin_detected", "coinjoin_protocol"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TxCharacteristics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TxCharacteristics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "input_script_types": obj.get("input_script_types"),
            "output_script_types": obj.get("output_script_types"),
            "n_inputs": obj.get("n_inputs"),
            "n_outputs": obj.get("n_outputs"),
            "total_input_sat": obj.get("total_input_sat"),
            "total_output_sat": obj.get("total_output_sat"),
            "fee_sat": obj.get("fee_sat"),
            "tx_version": obj.get("tx_version"),
            "locktime": obj.get("locktime"),
            "input_cluster_ids": obj.get("input_cluster_ids"),
            "coinjoin_detected": obj.get("coinjoin_detected") if obj.get("coinjoin_detected") is not None else False,
            "coinjoin_protocol": obj.get("coinjoin_protocol")
        })
        return _obj


