# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to blockchain analytics data across multiple ledgers. Use it to explore addresses, clusters, blocks, transactions, tags, token activity, and exchange-rate context, and to integrate investigation workflows into your own applications and automation.  ## Versioning & deprecation  The API follows semantic versioning. Minor releases are additive and backwards-compatible; breaking changes only happen in major releases, which are rare and announced in advance.  Deprecated endpoints and fields remain fully functional for at least six months after they are marked deprecated. During that window they are highlighted with a strikethrough in the docs and in generated clients, and responses from deprecated endpoints carry a `Deprecation` HTTP header that client tooling can detect. Replacement endpoints and fields are always introduced before the deprecated surface is removed.  See the [full versioning and deprecation policy](https://github.com/graphsense/graphsense-lib/blob/master/README.md#rest-api-evolution-and-deprecation-policy) for details.  ## AI assistant access (MCP)  In addition to this REST API, this deployment exposes a **Model Context Protocol (MCP)** interface that lets AI assistants query GraphSense directly in natural language, without writing code against the endpoints below.  The MCP interface is available at the `/mcp` path of this server, relative to the address this documentation is served from. It offers a curated selection of the most useful operations, so an assistant can answer questions about addresses, transactions, clusters, and tags on your behalf.  To use it, add that `/mcp` URL to an MCP-capable assistant as a new connector or tool source; the assistant then handles the rest.  **Authentication:** the MCP endpoint is protected by OAuth. When adding the connector in your assistant, use the client ID `iknaio-mcp`.   # noqa: E501

    Contact: contact@iknaio.com
    Generated by: https://openapi-generator.tech
"""

import warnings
from pydantic import Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from graphsense.models.graph_compare_request import GraphCompareRequest
from graphsense.models.graph_comparison import GraphComparison
from graphsense.models.graph_summary import GraphSummary
from graphsense.models.graph_summary_request import GraphSummaryRequest

from graphsense.api_client import ApiClient, RequestSerialized
from graphsense.api_response import ApiResponse
from graphsense.rest import RESTResponseType

# Backward compatibility wrapper for @validate_call to accept async_req
from functools import wraps
from datetime import datetime as _dt_compat
from pydantic import ConfigDict
_validate_call_config = ConfigDict(arbitrary_types_allowed=True)


class _AsyncResult:
    """v5-compatible async result wrapper around concurrent.futures.Future."""
    def __init__(self, future):
        self._future = future

    def get(self, timeout=None):
        """Block and return the result, like v5's ApplyResult.get()."""
        return self._future.result(timeout=timeout)

    def ready(self):
        """Check if the result is ready."""
        return self._future.done()

    def successful(self):
        """Check if the call completed without exception."""
        if not self._future.done():
            return False
        return self._future.exception() is None


def validate_call_compat(func):
    """Wrapper that filters out legacy kwargs like async_req before validation."""
    from pydantic import validate_call as _validate_call
    # Apply validate_call with config that allows arbitrary types
    validated_func = _validate_call(config=_validate_call_config)(func)
    @wraps(func)
    def wrapper(*args, **kwargs):
        # Capture async_req before removing it
        async_req = kwargs.pop('async_req', False)
        preload_content = kwargs.pop('_preload_content', None)
        kwargs.pop('_return_http_data_only', None)
        # Remap legacy 'body' kwarg to 'request_body' (v5 -> v7 migration)
        if 'body' in kwargs and 'request_body' not in kwargs:
            kwargs['request_body'] = kwargs.pop('body')
        # Convert datetime to date string for date parameters (backward compatibility)
        # Preserve full ISO 8601 format when datetime has time/timezone info
        for key in list(kwargs.keys()):
            if 'date' in key.lower() and isinstance(kwargs[key], _dt_compat):
                dt = kwargs[key]
                if dt.hour or dt.minute or dt.second or dt.tzinfo:
                    # Preserve full datetime with timezone (ISO 8601)
                    kwargs[key] = dt.isoformat()
                else:
                    # Date-only (midnight, no timezone) - use simple format
                    kwargs[key] = dt.strftime('%Y-%m-%d')
        # Also check positional args - var_date is typically arg[1]
        args = list(args)
        for i, arg in enumerate(args):
            if isinstance(arg, _dt_compat):
                if arg.hour or arg.minute or arg.second or arg.tzinfo:
                    args[i] = arg.isoformat()
                else:
                    args[i] = arg.strftime('%Y-%m-%d')

        # Handle async_req: submit to thread pool if available
        if async_req:
            # args[0] is self (the API instance), which has api_client
            api_instance = args[0]
            if hasattr(api_instance, 'api_client'):
                thread_pool = getattr(api_instance.api_client, '_thread_pool', None)
                if thread_pool is not None:
                    future = thread_pool.submit(validated_func, *args, **kwargs)
                    return _AsyncResult(future)
                else:
                    import warnings
                    warnings.warn(
                        "async_req=True but no thread pool available (pool_threads=0). "
                        "Running synchronously. Set pool_threads >= 1 for async execution.",
                        UserWarning
                    )
            # No thread pool available, fall through to sync call

        # Handle _preload_content=False by routing to _without_preload_content variant
        if preload_content is False:
            func_name = validated_func.__name__
            without_preload = func_name + '_without_preload_content'
            if args and hasattr(args[0], without_preload):
                return getattr(args[0], without_preload)(*args[1:], **kwargs)

        return validated_func(*args, **kwargs)
    return wrapper


class GraphApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call_compat
    def graph_compare(
        self,
        graph_compare_request: GraphCompareRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GraphComparison:
        """Compare multiple transactions (beta)

        **BETA**: this endpoint is new and its contract may still change without a deprecation cycle. Returns per-tx characteristics, pairwise similarity signals, and a rollup verdict on whether the supplied transactions are likely linked to the same actor. The fingerprinting analysis is BTC-only; every ref's network must be btc. For chain-agnostic aggregate stats over a node set use POST /graph/summary instead. Tx refs are canonicalized (hashes lowercased, 0x stripped) and duplicates collapsed; the response echoes the canonical hashes, and all positional references — signal per_tx entries and lineage from_idx/to_idx — index into the response's txs list, which may be shorter than the request's.

        :param graph_compare_request: (required)
        :type graph_compare_request: GraphCompareRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._graph_compare_serialize(
            graph_compare_request=graph_compare_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GraphComparison",
            '400': None,
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call_compat
    def graph_compare_with_http_info(
        self,
        graph_compare_request: GraphCompareRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GraphComparison]:
        """Compare multiple transactions (beta)

        **BETA**: this endpoint is new and its contract may still change without a deprecation cycle. Returns per-tx characteristics, pairwise similarity signals, and a rollup verdict on whether the supplied transactions are likely linked to the same actor. The fingerprinting analysis is BTC-only; every ref's network must be btc. For chain-agnostic aggregate stats over a node set use POST /graph/summary instead. Tx refs are canonicalized (hashes lowercased, 0x stripped) and duplicates collapsed; the response echoes the canonical hashes, and all positional references — signal per_tx entries and lineage from_idx/to_idx — index into the response's txs list, which may be shorter than the request's.

        :param graph_compare_request: (required)
        :type graph_compare_request: GraphCompareRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._graph_compare_serialize(
            graph_compare_request=graph_compare_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GraphComparison",
            '400': None,
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call_compat
    def graph_compare_without_preload_content(
        self,
        graph_compare_request: GraphCompareRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Compare multiple transactions (beta)

        **BETA**: this endpoint is new and its contract may still change without a deprecation cycle. Returns per-tx characteristics, pairwise similarity signals, and a rollup verdict on whether the supplied transactions are likely linked to the same actor. The fingerprinting analysis is BTC-only; every ref's network must be btc. For chain-agnostic aggregate stats over a node set use POST /graph/summary instead. Tx refs are canonicalized (hashes lowercased, 0x stripped) and duplicates collapsed; the response echoes the canonical hashes, and all positional references — signal per_tx entries and lineage from_idx/to_idx — index into the response's txs list, which may be shorter than the request's.

        :param graph_compare_request: (required)
        :type graph_compare_request: GraphCompareRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._graph_compare_serialize(
            graph_compare_request=graph_compare_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GraphComparison",
            '400': None,
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _graph_compare_serialize(
        self,
        graph_compare_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if graph_compare_request is not None:
            _body_params = graph_compare_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/graph/compare',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call_compat
    def graph_summary(
        self,
        graph_summary_request: GraphSummaryRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GraphSummary:
        """Summarize a set of transactions and/or addresses (beta)

        **BETA**: this endpoint is new and its contract may still change without a deprecation cycle. Returns aggregate stats over the transactions and/or addresses in the request body. Every item carries its own network, so the set may span chains. Each node-type block holds a network-agnostic overall part (fiat totals per code, timestamp span) and one full per-network block (native base-unit values via the Values pattern) per network in the request. Each block is present iff the request carried that node type. Each non-empty list must hold at least 2 distinct entries; together they may hold at most 100. References are canonicalized before processing (tx hashes lowercased, 0x stripped; addresses network-canonicalized), and duplicates — including spelling variants of one node — are collapsed and counted once. Unknown references are dropped and reported per network in a nodes_not_found note (its items list carries the refs); the request only fails when fewer than 2 of a list's references exist. Value totals are gross: UTXO txs contribute their full output sum (change included), so sets containing linked txs (e.g. a peel chain) count the same coins once per hop.

        :param graph_summary_request: (required)
        :type graph_summary_request: GraphSummaryRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._graph_summary_serialize(
            graph_summary_request=graph_summary_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GraphSummary",
            '400': None,
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call_compat
    def graph_summary_with_http_info(
        self,
        graph_summary_request: GraphSummaryRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GraphSummary]:
        """Summarize a set of transactions and/or addresses (beta)

        **BETA**: this endpoint is new and its contract may still change without a deprecation cycle. Returns aggregate stats over the transactions and/or addresses in the request body. Every item carries its own network, so the set may span chains. Each node-type block holds a network-agnostic overall part (fiat totals per code, timestamp span) and one full per-network block (native base-unit values via the Values pattern) per network in the request. Each block is present iff the request carried that node type. Each non-empty list must hold at least 2 distinct entries; together they may hold at most 100. References are canonicalized before processing (tx hashes lowercased, 0x stripped; addresses network-canonicalized), and duplicates — including spelling variants of one node — are collapsed and counted once. Unknown references are dropped and reported per network in a nodes_not_found note (its items list carries the refs); the request only fails when fewer than 2 of a list's references exist. Value totals are gross: UTXO txs contribute their full output sum (change included), so sets containing linked txs (e.g. a peel chain) count the same coins once per hop.

        :param graph_summary_request: (required)
        :type graph_summary_request: GraphSummaryRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._graph_summary_serialize(
            graph_summary_request=graph_summary_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GraphSummary",
            '400': None,
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call_compat
    def graph_summary_without_preload_content(
        self,
        graph_summary_request: GraphSummaryRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Summarize a set of transactions and/or addresses (beta)

        **BETA**: this endpoint is new and its contract may still change without a deprecation cycle. Returns aggregate stats over the transactions and/or addresses in the request body. Every item carries its own network, so the set may span chains. Each node-type block holds a network-agnostic overall part (fiat totals per code, timestamp span) and one full per-network block (native base-unit values via the Values pattern) per network in the request. Each block is present iff the request carried that node type. Each non-empty list must hold at least 2 distinct entries; together they may hold at most 100. References are canonicalized before processing (tx hashes lowercased, 0x stripped; addresses network-canonicalized), and duplicates — including spelling variants of one node — are collapsed and counted once. Unknown references are dropped and reported per network in a nodes_not_found note (its items list carries the refs); the request only fails when fewer than 2 of a list's references exist. Value totals are gross: UTXO txs contribute their full output sum (change included), so sets containing linked txs (e.g. a peel chain) count the same coins once per hop.

        :param graph_summary_request: (required)
        :type graph_summary_request: GraphSummaryRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._graph_summary_serialize(
            graph_summary_request=graph_summary_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GraphSummary",
            '400': None,
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _graph_summary_serialize(
        self,
        graph_summary_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if graph_summary_request is not None:
            _body_params = graph_summary_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/graph/summary',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


